main: Fludixx\Sagiri_chan\SagiriAPI
name: "Sagiri-API"
version: 0.3
description: "Sagiri-chan API for your Server"
api: 3.0.0
author: Fludixx
permissions:
  sagiri.administrative:
    default: op
    description: "Ban, mute & Report Permissions"
